spring.application.name=financas-a-dois

# Server port
# Local: uses 8080 by default.
# Koyeb: uses the PORT environment variable.
server.port=${PORT:8080}


# PostgreSQL
# Local:
# If DB_URL and DB_USERNAME are not defined,
# the application uses the local PostgreSQL database.
#
# Production:
# Koyeb will provide DB_URL, DB_USERNAME and DB_PASSWORD
# pointing to Neon.

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/financas_a_dois}
spring.datasource.username=${DB_USERNAME:financas_app}
spring.datasource.password=${DB_PASSWORD}


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# Application users
# Passwords remain outside the source code.
app.kleber.password=${KLEBER_APP_PASSWORD}
app.giovanna.password=${GIOVANNA_APP_PASSWORD}